spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://192.168.88.230:3306/splider?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: org.gjt.mm.mysql.Driver
  dubbo:
        application:
          name: service-provider
        base-package: com.chenlink.euterpe.mybatis.service.impl  # dubbo服务发布者实现类注解@service所在的包
        registry:
          address: 127.0.0.1                   # zookeeper注册中心的地址
          port: 2181                           # zookeeper注册中心的端口
        protocol:
          name: dubbo
          serialization: hessian2
        provider:
          retries: 0                             # 服务调用重试次数，服务发布者不给重试，让服务调用者自己重试
  redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
    database: 3
    # redis服务器地址（默认为localhost）
    host: localhost
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password:
    # redis连接超时时间（单位为毫秒）
    timeout: 0
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1

# 服务器配置
server:
  port: 9999

# mybatis配置
mybatis:
  # 配置映射类所在包名
  type-aliases-package: com.chenlink.euterpe.entity
  # 配置mapper xml文件所在路径，这里是一个数组
  mapper-locations:
    - mappers/BillCycleMapper.xml
    - mappers/MobileOperatorMapper.xml


logging:
  level:
    com.wooyoo.learning: DEBUG

#---
#spring:
#  profiles: test
#  # 数据库配置
#  datasource:
#    url: jdbc:h2:mem:test
#    username: root
#    password: 123456
#    driver-class-name: org.h2.Driver
#    schema: classpath:schema.sql
#    data: classpath:data.sql


